
Model 1
==========
colorOf := {(A, A) -> Red, (A, B) -> Red, (A, C) -> Red, (A, D) -> Red, (B, A) -> Red, (B, B) -> Red, (B, C) -> Red, (B, D) -> Red, (C, A) -> Red, (C, B) -> Red, (C, C) -> Red, (C, D) -> Red, (D, A) -> Red, (D, B) -> Red, (D, C) -> Red, (D, D) -> Red}.
_monochrome_triangle := {(A, B, C), (A, B, D), (A, C, B), (A, C, D), (A, D, B), (A, D, C), (B, A, C), (B, A, D), (B, C, A), (B, C, D), (B, D, A), (B, D, C), (C, A, B), (C, A, D), (C, B, A), (C, B, D), (C, D, A), (C, D, B), (D, A, B), (D, A, C), (D, B, A), (D, B, C), (D, C, A), (D, C, B)}.


More models may be available.  Change the max argument to see them.
