test:
    image: ubuntu
    script:
        - apt update
        - apt -y install python3 python3-pip git
        - pip3 install -r requirements.txt
        - python3 test.py pipeline

pages:
  image: ubuntu
  stage: deploy
  script:
    - apt update
    - apt -y install python3 git
    - python3 get-poetry.py
    - poetry install
    - poetry run sphinx-build homepage public
  artifacts:
    paths:
    - public
  only:
  - main
