runtime: python38
entrypoint: gunicorn -b :$PORT main:app --timeout 90 # timeout after 90 sec

instance_class: F4
automatic_scaling:
  max_instances: 10 # to manage costs !
  max_concurrent_requests: 1 # Z3 not threadsafe ! but possibly costly !
  min_pending_latency: 300ms # default: 30ms

handlers:
  - url: /$
    static_files: consultant/static/index.html
    require_matching_file: false
    upload: consultant/static/index.html
  - url: /examples/(.*)
    static_files: consultant/examples/\1
    require_matching_file: false
    upload: consultant/examples/.*
  - url: /assets//(.*) # to fix bug in client
    static_files: consultant/static/assets/\1
    require_matching_file: false
    upload: consultant/static/assets/.*
  - url: /assets/(.*)
    static_files: consultant/static/assets/\1
    require_matching_file: false
    upload: consultant/static/assets/.*
  - url: /meta
    script: auto
    secure: always
    redirect_http_response_code: '301'
  - url: /eval
    script: auto
    secure: always
    redirect_http_response_code: '301'
  - url: /(.*)
    static_files: consultant/static/\1
    require_matching_file: false
    upload: consultant/static/.*
  - url: .*
    script: auto