runtime: python38

instance_class: F4
automatic_scaling:
  max_instances: 10 # to manage costs !
  max_concurrent_requests: 1 # Z3 not threadsafe ! but possibly costly !
  min_pending_latency: 300ms # default: 30ms

handlers:

  - url: /$
    static_files: consultant/static/index.html

  - url: /examples
    static_dir: consultant/examples

  - url: /assets
    static_dir: consultant/static/assets

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto