Sides := 3.
Vertices := 3.
Type := triangle.
Length := {1 -> 1.0, 2 -> 1.0, 3 -> 1.0, 4 -> 0.0}.
Angle := {1 -> 60.0, 2 -> 60.0, 3 -> 60.0, 4 -> 0.0}.
Subtype := regular_triangle.
Convex := true.
Equilateral := true.
Perimeter := 3.
Base := 8.
Height := 9.
Surface := 10.

Sides := 3.
Vertices := 3.
Type := triangle.
Length := {1 -> 1.0, 2 -> 1.0, 3 -> 1.0, 4 -> 0.0}.
Angle := {1 -> 60.0, 2 -> 60.0, 3 -> 60.0, 4 -> 0.0}.
Subtype := regular_triangle.
Convex := true.
Equilateral := true.
Perimeter := 3.
Base := 8.
Height := 9.
Surface := 10.


Model 1
==========
Sides := 3.
Vertices := 3.
Type := triangle.
Length := {1 -> 1.0, 2 -> 1.0, 3 -> 1.0, 4 -> 0.0}.
Angle := {1 -> 60.0, 2 -> 60.0, 3 -> 60.0, 4 -> 0.0}.
Subtype := regular_triangle.
Convex := true.
Equilateral := true.
Perimeter := 3.
Large := {}.
Wide := {}.
Base := 8.
Height := 9.
Surface := 10.


More models may be available.  Change the max argument to see them.
