
Model 1
==========
green := {B3}.
right := {}.


Model 2
==========
green := {B3}.
right := {}.


Model 3
==========
green := {B3}.
right := {}.


Model 4
==========
green := {B3}.
right := {}.


Model 5
==========
green := {B3}.
right := {}.


Model 6
==========
green := {B3}.
right := {}.


Model 7
==========
green := {B3}.
right := {}.


Model 8
==========
green := {B3}.
right := {}.


Model 9
==========
green := {B3}.
right := {}.


Model 10
==========
green := {B3}.
right := {}.


More models may be available.  Change the max argument to see them.
