
Model 1
==========
gridSize := 2.
_add := {(pos(1, 1), pos(1, 1)) -> pos(2, 2), (pos(1, 1), pos(1, 2)) -> pos(2, 2), (pos(1, 1), pos(2, 1)) -> pos(2, 2), (pos(1, 1), pos(2, 2)) -> pos(2, 2), (pos(1, 2), pos(1, 1)) -> pos(2, 2), (pos(1, 2), pos(1, 2)) -> pos(2, 2), (pos(1, 2), pos(2, 1)) -> pos(2, 2), (pos(1, 2), pos(2, 2)) -> pos(2, 2), (pos(2, 1), pos(1, 1)) -> pos(2, 2), (pos(2, 1), pos(1, 2)) -> pos(2, 2), (pos(2, 1), pos(2, 1)) -> pos(2, 2), (pos(2, 1), pos(2, 2)) -> pos(2, 2), (pos(2, 2), pos(1, 1)) -> pos(2, 2), (pos(2, 2), pos(1, 2)) -> pos(2, 2), (pos(2, 2), pos(2, 1)) -> pos(2, 2), (pos(2, 2), pos(2, 2)) -> pos(2, 2)}.
x1 := 2.
p := pos(2, 2).
clip >> {4 -> 2, 3 -> 2}.
makePos >> {(3, 3) -> pos(2, 2)}.


No more models.
