gebeurtenis() -> huwelijk
persoon() -> zelf
Not federaal_ambtenaar()
_window(#2023-05-08)
_window(#2023-05-09)
_window(#2023-05-10)
_window(#2023-05-11)
_window(#2023-05-12)
dagen_verlet() -> 2
? opgenomen(#2023-05-08)
? opgenomen(#2023-05-09)
? opgenomen(#2023-05-10)
? opgenomen(#2023-05-11)
? opgenomen(#2023-05-12)
van_toepassing(1)
Not van_toepassing(4)
Not van_toepassing(15)
gebeurtenis() = huwelijk
persoon() = zelf
dagen_verlet() = 2
Not gebeurtenis() = overlijden
Not persoon() in {echtgenoot, samenwonende_partner, feitelijk_samenwonende_partner, kind}
Not dagen_verlet() = 10
Not gebeurtenis() = familieraad
Not dagen_verlet() = 0
