Traceback (most recent call last):
  File "textx/model.py", line ??, in _parse
    return self.parser_model.parse(self)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = [self.nodes[0].parse(parser)]
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = p(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = p(parser)
  File "arpeggio/__init__.py", line ??, in parse
    raise parser.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = p(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = p(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = p(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = p(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = p(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = p(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = p(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = p(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = p(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = p(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = p(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = p(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line ??, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line ??, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line ??, in _nm_raise
    raise self.nm
arpeggio.NoMatch: Expected '(' or '^' or '⨯' or '*' or '/' or '%' or '+' or '-' or '=<' or '>=' or '~=' or '=' or '<' or '>' or '≤' or '≥' or '≠' or '&' or '∧' or '|' or '∨' or '=>' or '⇒' or '<=>' or '⇔' or '<=' or '⇐' or '.' at position (29, 21) => 'nt() = sum*{ Bus in B'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line ??, in generateZ3
    idp = IDP.from_str(theory)
  File "idp_engine/Parse.py", line ??, in from_str
    out = idpparser.model_from_str(code)
  File "textx/metamodel.py", line ??, in model_from_str
    model = self._parser_blueprint.clone().get_model_from_str(
  File "textx/model.py", line ??, in get_model_from_str
    self.parse(model_str, file_name=file_name)
  File "arpeggio/__init__.py", line ??, in parse
    self.parse_tree = self._parse()
  File "textx/model.py", line ??, in _parse
    raise TextXSyntaxError(message=text(e),
textx.exceptions.TextXSyntaxError: None:29:21: error: Expected '(' or '^' or '⨯' or '*' or '/' or '%' or '+' or '-' or '=<' or '>=' or '~=' or '=' or '<' or '>' or '≤' or '≥' or '≠' or '&' or '∧' or '|' or '∨' or '=>' or '⇒' or '<=>' or '⇔' or '<=' or '⇐' or '.' at position (29, 21) => 'nt() = sum*{ Bus in B'.

