opposite(red) = green ∧ opposite(green) = red ∧ Color in {red,green, green,red} ∧ (Color = red ∨ Color = blue ∨ Color = green) ∧ (opposite(red) = red ∨ opposite(red) = blue ∨ opposite(red) = green) ∧ (opposite(blue) = red ∨ opposite(blue) = blue ∨ opposite(blue) = green) ∧ (opposite(green) = red ∨ opposite(green) = blue ∨ opposite(green) = green) ∧ true

Model 1
==========
Color:={->red}
opposite:={(red)->green; (blue)->red; (green)->red}

Model 2
==========
Color:={->green}
opposite:={(red)->green; (blue)->red; (green)->red}

Model 3
==========
Color:={->green}
opposite:={(red)->green; (blue)->blue; (green)->red}

Model 4
==========
Color:={->green}
opposite:={(red)->green; (blue)->green; (green)->red}

Model 5
==========
Color:={->red}
opposite:={(red)->green; (blue)->green; (green)->red}

Model 6
==========
Color:={->red}
opposite:={(red)->green; (blue)->blue; (green)->red}

No more models.
