opposite(red) = green ∧ opposite(green) = red ∧ Color in {red,green, green,red} ∧ (Color = red ∨ Color = blue ∨ Color = green ∨ Color = rgb(1) ∨ Color = rgb(2)) ∧ (opposite(red) = red ∨ opposite(red) = blue ∨ opposite(red) = green ∨ opposite(red) = rgb(1) ∨ opposite(red) = rgb(2)) ∧ (opposite(blue) = red ∨ opposite(blue) = blue ∨ opposite(blue) = green ∨ opposite(blue) = rgb(1) ∨ opposite(blue) = rgb(2)) ∧ (opposite(green) = red ∨ opposite(green) = blue ∨ opposite(green) = green ∨ opposite(green) = rgb(1) ∨ opposite(green) = rgb(2)) ∧ (opposite(rgb(1)) = red ∨ opposite(rgb(1)) = blue ∨ opposite(rgb(1)) = green ∨ opposite(rgb(1)) = rgb(1) ∨ opposite(rgb(1)) = rgb(2)) ∧ (opposite(rgb(2)) = red ∨ opposite(rgb(2)) = blue ∨ opposite(rgb(2)) = green ∨ opposite(rgb(2)) = rgb(1) ∨ opposite(rgb(2)) = rgb(2)) ∧ true

Model 1
==========
Color:={->red}
opposite:={(red)->green; (blue)->red; (green)->red; (rgb(1))->red; (rgb(2))->red}

More models are available.
