Sides:={->3}
Vertices:={->3}
f:={3->#2021-05-31; 4->#2021-05-31}
Type:={->triangle}
Length:={1->0.0021676912394790766; 2->0.003251536859218615; 3->0.0021676912394790766; 4->0}
Angle:={1->90; 2->59.99891615438026; 3->30.00108384561974; 4->0}
Subtype:={->right_triangle}
Convex:={->true}
Equilateral:={->false}
Perimeter:={->0.00650307371843723}
Large:={1->false; 2->false; 3->false; 4->false}
Wide:={1->false; 2->false; 3->false; 4->false}
Base:={->0}
Height:={->0}
Surface:={->0}

Model 1
==========
Sides:={->3}
Vertices:={->3}
f:={3->#2021-05-31; 4->#0001-01-06}
Type:={->triangle}
Length:={1->1; 2->1; 3->1; 4->0}
Angle:={1->60; 2->60; 3->60; 4->0}
Subtype:={->regular_triangle}
Convex:={->true}
Equilateral:={->true}
Perimeter:={->3}
Large:={1->false; 2->false; 3->false; 4->false}
Wide:={1->false; 2->false; 3->false; 4->false}
Base:={->6}
Height:={->6}
Surface:={->6}

More models are available.
