Sides:={->3}
Vertices:={->3}
f:={(3)->#2021-04-28; (4)->#2021-04-28}
Type:={->triangle}
Length:={(1)->0.006172839506172839; (2)->0.0030864197530864196; (3)->0.009259259259259259; (4)->0}
Angle:={(1)->29.996913580246915; (2)->90; (3)->60.00308641975309; (4)->0}
Subtype:={->right_triangle}
Convex:={->true}
Equilateral:={->false}
Perimeter:={->0.018518518518518517}

Model 1
==========
Sides:={->3}
Vertices:={->3}
f:={(3)->#2021-04-28; (4)->#2021-04-28}
Type:={->triangle}
Length:={(1)->1; (2)->1; (3)->1; (4)->0}
Angle:={(1)->60; (2)->60; (3)->60; (4)->0}
Subtype:={->regular_triangle}
Convex:={->true}
Equilateral:={->true}
Perimeter:={->3}
Large:={(1)->false; (2)->false; (3)->false; (4)->false}
Wide:={(1)->false; (2)->false; (3)->false; (4)->false}
Base:={->0}
Height:={->0}
Surface:={->0}

More models are available.
