Sides:={->3}
Vertices:={->3}
Type:={->triangle}
Length:={1->0.3333333333333333; 2->0.3333333333333333; 3->0.3333333333333333; 4->0}
Angle:={1->60; 2->60; 3->60; 4->0}
Subtype:={->regular_triangle}
Convex:={->true}
Equilateral:={->true}
Perimeter:={->1}
Large:={1->false; 2->false; 3->false; 4->false}
Wide:={1->false; 2->false; 3->false; 4->false}
Base:={->0}
Height:={->0}
Surface:={->0}

Model 1
==========
Sides:={->3}
Vertices:={->3}
Type:={->triangle}
Length:={1->0.3333333333333333; 2->0.3333333333333333; 3->0.3333333333333333; 4->0}
Angle:={1->60; 2->60; 3->60; 4->0}
Subtype:={->regular_triangle}
Convex:={->true}
Equilateral:={->true}
Perimeter:={->1}
Large:={1->false; 2->false; 3->false; 4->false}
Wide:={1->false; 2->false; 3->false; 4->false}
Base:={->4}
Height:={->4}
Surface:={->4}

More models are available.
