
Model 1
==========
Color:={->green}
opposite:={(red)->green; (blue)->blue; (green)->red}

Model 2
==========
Color:={->green}
opposite:={(red)->green; (blue)->green; (green)->red}

Model 3
==========
Color:={->green}
opposite:={(red)->green; (blue)->red; (green)->red}

Model 4
==========
Color:={->red}
opposite:={(red)->green; (blue)->blue; (green)->red}

Model 5
==========
Color:={->red}
opposite:={(red)->green; (blue)->green; (green)->red}

Model 6
==========
Color:={->red}
opposite:={(red)->green; (blue)->red; (green)->red}

No more models.

Model 1
==========
Color:={->A}
opposite:={(A)->C; (B)->A; (C)->A}

Model 2
==========
Color:={->A}
opposite:={(A)->C; (B)->B; (C)->A}

Model 3
==========
Color:={->A}
opposite:={(A)->C; (B)->C; (C)->A}

Model 4
==========
Color:={->C}
opposite:={(A)->C; (B)->A; (C)->A}

Model 5
==========
Color:={->C}
opposite:={(A)->C; (B)->B; (C)->A}

Model 6
==========
Color:={->C}
opposite:={(A)->C; (B)->C; (C)->A}

No more models.
