
Model 1
==========
p := {0, -1}.


Model 2
==========
p := {0, -1, -2}.


Model 3
==========
p := {0}.


Model 4
==========
p := {0, 2}.


Model 5
==========
p := {0, 2, 3}.


Model 6
==========
p := {0, 2, 3, 4, 1}.


Model 7
==========
p := {0, 2, 3, 4, 1, 5}.


Model 8
==========
p := {0, 2, 3, 4, 1, 5, 6}.


Model 9
==========
p := {0, 2, 3, 4, 1, 5, 6, 7}.


Model 10
==========
p := {0, 2, 3, 4, 1, 5, 6, 7, 8}.


More models may be available.  Change the max argument to see them.
