[ Not HasRating(s) ≤ 77
  Not Eligible(BE001) ]
[ Issuer(s) in {BRITISHCOLUMBIA, TORONTO, MANITOBA, NEWBRUNsELEC, NEWBRUNSWICK, NEWFOUNDLAND, NOVASCOTIA, ONTARIO, PRINCEEDWARDISLD, ALBERTA, QUEBEC, SASKATCHEWAN}
  Not AssetSubClass(s) = ABS
  Eligible(BE001) ]
[ Country(s) in {Aus, Bel, Can, Den, Est, Fin, Fra, Ger, Hon, Ire, Isr, Ita, Jap, Lux, Net, New, Nor, Por, Sin, Slo, Sou, Spa, Swe, Swi, UniK, UniS}
  Issuer_Type(s) = Sovereign
  Eligible(BE001) ]
[ Issuer(s) in {BRITISHCOLUMBIA, TORONTO, MANITOBA, NEWBRUNsELEC, NEWBRUNSWICK, NEWFOUNDLAND, NOVASCOTIA, ONTARIO, PRINCEEDWARDISLD, ALBERTA, QUEBEC, SASKATCHEWAN}
  Not Eligible(BE001) ]
[ Issuer(s) in {AfricanDevelopmentBank, AsianDevelopmentBank, BankForInternationalSettlements, CaribbeanDevelopmentBank, CouncilOfEuropeDevelopmentBank, EuropeanBankForReconstructionAndDevelopment, EuropeanCentralBank, EuropeanInvestmentBank, EuropeanInvestmentFund, InterAmericanDevelopmentBank, InternationalBankForReconstructionAndDevelopment, InternationalFinanceCorporation, InternationalMonetaryFund, MultilateralInvestmentGuaranteeAgency, NordicInvestmentBank}
  Issuer_Type(s) = Supra
  Eligible(BE001) ]
[ Issuer(s) in {GovernmentNationalMortgageAssociation, FederalHomeLoanMortgageCorporation, FederalNationalMortgageAssociation}
  Not Issuer(s) in {AfricanDevelopmentBank, AsianDevelopmentBank, BankForInternationalSettlements, CaribbeanDevelopmentBank, CouncilOfEuropeDevelopmentBank, EuropeanBankForReconstructionAndDevelopment, EuropeanCentralBank, EuropeanInvestmentBank, EuropeanInvestmentFund, InterAmericanDevelopmentBank, InternationalBankForReconstructionAndDevelopment, InternationalFinanceCorporation, InternationalMonetaryFund, MultilateralInvestmentGuaranteeAgency, NordicInvestmentBank}
  Not AssetSubClass(s) = ABS
  Eligible(BE001) ]
