[ Not HasRating(BE001) ≤ 77
  Not Eligible(BE001) ]
[ Not AssetSubClass(BE001) = ABS
  Issuer(BE001) = ALBERTA ∨ Issuer(BE001) = BRITISHCOLUMBIA ∨ Issuer(BE001) = MANITOBA ∨ Issuer(BE001) = NEWBRUNSWICK ∨ Issuer(BE001) = NEWBRUNsELEC ∨ Issuer(BE001) = NEWFOUNDLAND ∨ Issuer(BE001) = NOVASCOTIA ∨ Issuer(BE001) = ONTARIO ∨ Issuer(BE001) = PRINCEEDWARDISLD ∨ Issuer(BE001) = QUEBEC ∨ Issuer(BE001) = SASKATCHEWAN ∨ Issuer(BE001) = TORONTO
  Eligible(BE001) ]
[ Not AssetSubClass(BE001) = ABS
  Issuer(BE001) = FederalHomeLoanMortgageCorporation ∨ Issuer(BE001) = FederalNationalMortgageAssociation ∨ Issuer(BE001) = GovernmentNationalMortgageAssociation
  Eligible(BE001) ]
[ Country(BE001) = Aus ∨ Country(BE001) = Bel ∨ Country(BE001) = Can ∨ Country(BE001) = Den ∨ Country(BE001) = Est ∨ Country(BE001) = Fin ∨ Country(BE001) = Fra ∨ Country(BE001) = Ger ∨ Country(BE001) = Hon ∨ Country(BE001) = Ire ∨ Country(BE001) = Isr ∨ Country(BE001) = Ita ∨ Country(BE001) = Jap ∨ Country(BE001) = Lux ∨ Country(BE001) = Net ∨ Country(BE001) = New ∨ Country(BE001) = Nor ∨ Country(BE001) = Por ∨ Country(BE001) = Sin ∨ Country(BE001) = Slo ∨ Country(BE001) = Sou ∨ Country(BE001) = Spa ∨ Country(BE001) = Swe ∨ Country(BE001) = Swi ∨ Country(BE001) = UniK ∨ Country(BE001) = UniS
  Issuer_Type(BE001) = Sovereign
  Eligible(BE001) ]
[ Not Issuer(BE001) = AfricanDevelopmentBank ∨ Issuer(BE001) = AsianDevelopmentBank ∨ Issuer(BE001) = BankForInternationalSettlements ∨ Issuer(BE001) = CaribbeanDevelopmentBank ∨ Issuer(BE001) = CouncilOfEuropeDevelopmentBank ∨ Issuer(BE001) = EuropeanBankForReconstructionAndDevelopment ∨ Issuer(BE001) = EuropeanCentralBank ∨ Issuer(BE001) = EuropeanInvestmentBank ∨ Issuer(BE001) = EuropeanInvestmentFund ∨ Issuer(BE001) = InterAmericanDevelopmentBank ∨ Issuer(BE001) = InternationalBankForReconstructionAndDevelopment ∨ Issuer(BE001) = InternationalFinanceCorporation ∨ Issuer(BE001) = InternationalMonetaryFund ∨ Issuer(BE001) = MultilateralInvestmentGuaranteeAgency ∨ Issuer(BE001) = NordicInvestmentBank
  Not Eligible(BE001) ]
[ Not Issuer_Type(BE001) = Supra
  Not Eligible(BE001) ]
