
Model 1
==========
Q := {a, b}.
p := {a}.
f := {(a, a) -> a, (b, a) -> a}.


Model 2
==========
Q := {a}.
p := {a, b}.
f := {(a, a) -> a, (a, b) -> a}.


Model 3
==========
Q := {a}.
p := {a}.
f := {(a, a) -> a}.


Model 4
==========
Q := {a}.
p := {a, b}.
f := {(a, a) -> a, (a, b) -> b}.


Model 5
==========
Q := {a, b}.
p := {a, b}.
f := {(a, a) -> a, (a, b) -> a, (b, a) -> a, (b, b) -> b}.


Model 6
==========
Q := {a, b}.
p := {a, b}.
f := {(a, a) -> a, (a, b) -> a, (b, a) -> b, (b, b) -> b}.


Model 7
==========
Q := {a, b}.
p := {a, b}.
f := {(a, a) -> a, (a, b) -> b, (b, a) -> b, (b, b) -> b}.


Model 8
==========
Q := {a, b}.
p := {a, b}.
f := {(a, a) -> a, (a, b) -> b, (b, a) -> a, (b, b) -> b}.


Model 9
==========
Q := {a, b}.
p := {a}.
f := {(a, a) -> a, (b, a) -> b}.


No more models.
