
Model 1
==========
q := {(a, b), (b, c), (d, e)}.
f := 13.
p := {(a, a), (a, b), (a, c), (b, a), (b, b), (b, c), (c, a), (c, b), (c, c), (d, d), (d, e), (e, d), (e, e)}.


No more models.
q := {(a, b), (b, c), (d, e)}.
// f := *.
p := {(b, a), (c, a), (c, b), (e, d)}.


Model 1
==========
q := {(a, b), (b, c), (d, e)}.
f := 13.
p := {(a, a), (a, b), (a, c), (b, a), (b, b), (b, c), (c, a), (c, b), (c, c), (d, d), (d, e), (e, d), (e, e)}.


No more models.
q := {(a, b), (b, c), (d, e)}.
f := 13.

