
Model 1
==========
on := {}
put := {}
remove := {}
fluent := {(`on,false,`on,`on), (`on,false,`on,`put), (`on,false,`on,`remove), (`on,false,`put,`on), (`on,false,`put,`put), (`on,false,`put,`remove), (`on,false,`remove,`on), (`on,false,`remove,`put), (`on,false,`remove,`remove), (`put,false,`on,`on), (`put,false,`on,`put), (`put,false,`on,`remove), (`put,false,`put,`on), (`put,false,`put,`put), (`put,false,`put,`remove), (`put,false,`remove,`on), (`put,false,`remove,`put), (`put,false,`remove,`remove), (`remove,false,`on,`on), (`remove,false,`on,`put), (`remove,false,`on,`remove), (`remove,false,`put,`on), (`remove,false,`put,`put), (`remove,false,`put,`remove), (`remove,false,`remove,`on), (`remove,false,`remove,`put), (`remove,false,`remove,`remove)}


More models may be available.  Change the max argument to see them.
