
Model 1
==========
amount_thresholdEU := 1
periodEU := 0
amount_threshold := {Belgium->0, France->0}
period := {Belgium->-1, France->-1}
obligation := {`amount_threshold, `period}
mapping := {`𝔹->`𝔹, `ℤ->`𝔹, `ℝ->`𝔹, `Date->`𝔹, `Concept->`𝔹, `Country->`𝔹, `amount_thresholdEU->`𝔹, `periodEU->`𝔹, `amount_threshold->`amount_thresholdEU, `period->`periodEU, `obligation->`𝔹, `mapping->`𝔹}


More models may be available.  Change the max argument to see them.
