
Model 1
==========
amount_thresholdEU:={->1}
periodEU:={->0}
amount_threshold:={Belgium->0; France->0}
period:={Belgium->-1; France->-1}
obligation:={`𝔹->false; `ℤ->false; `ℝ->false; `Date->false; `Symbol->false; `Country->false; `amount_thresholdEU->false; `periodEU->false; `amount_threshold->true; `period->true; `obligation->false; `mapping->false}
mapping:={`𝔹->`𝔹; `ℤ->`𝔹; `ℝ->`𝔹; `Date->`𝔹; `Symbol->`𝔹; `Country->`𝔹; `amount_thresholdEU->`𝔹; `periodEU->`𝔹; `amount_threshold->`amount_thresholdEU; `period->`periodEU; `obligation->`𝔹; `mapping->`𝔹}

More models are available.
