
Model 1
==========
last := 1.
finishTime := 8.


Model 2
==========
last := 2.
finishTime := 8.


Model 3
==========
last := 3.
finishTime := 8.


Model 4
==========
last := 4.
finishTime := 8.


Model 5
==========
last := 5.
finishTime := 8.


Model 6
==========
last := 6.
finishTime := 8.


Model 7
==========
last := 7.
finishTime := 8.


Model 8
==========
last := 8.
finishTime := 8.


Model 9
==========
last := 0.
finishTime := 8.


No more models.
