.. index:: main block

Main block
----------

UNDER CONSTRUCTION

The *main block* consists of python-like statements to be executed by the IDP-Z3 executable or the Web IDE, in the context of the knowledge base.
It takes the following form:

.. code-block::

    procedure main() {
        // here comes the python-like code to be executed
    }

The following functions are available:

print(...)
    prints the arguments on stdout

