max() -> 4
has_mine(0, 0) -> 0
has_mine(0, 0) = 0
Not has_mine(0, 0) = 1
has_mine(0, 1) -> 0
has_mine(0, 1) = 0
Not has_mine(0, 1) = 1
has_mine(0, 2) -> 0
has_mine(0, 2) = 0
Not has_mine(0, 2) = 1
has_mine(0, 3) -> 0
has_mine(0, 3) = 0
Not has_mine(0, 3) = 1
has_mine(0, 4) -> 0
has_mine(0, 4) = 0
Not has_mine(0, 4) = 1
has_mine(1, 0) -> 0
has_mine(1, 0) = 0
Not has_mine(1, 0) = 1
has_mine(1, 4) -> 0
has_mine(1, 4) = 0
Not has_mine(1, 4) = 1
has_mine(2, 0) -> 0
has_mine(2, 0) = 0
Not has_mine(2, 0) = 1
has_mine(2, 4) -> 0
has_mine(2, 4) = 0
Not has_mine(2, 4) = 1
has_mine(3, 0) -> 0
has_mine(3, 0) = 0
Not has_mine(3, 0) = 1
has_mine(3, 4) -> 0
has_mine(3, 4) = 0
Not has_mine(3, 4) = 1
has_mine(4, 0) -> 0
has_mine(4, 0) = 0
Not has_mine(4, 0) = 1
has_mine(4, 1) -> 0
has_mine(4, 1) = 0
Not has_mine(4, 1) = 1
has_mine(4, 2) -> 0
has_mine(4, 2) = 0
Not has_mine(4, 2) = 1
has_mine(4, 3) -> 0
has_mine(4, 3) = 0
Not has_mine(4, 3) = 1
has_mine(4, 4) -> 0
has_mine(4, 4) = 0
Not has_mine(4, 4) = 1
count(0, 0) -> 0
count(0, 0) = 0
Not count(0, 0) = 1
Not count(0, 0) = 2
Not count(0, 0) = 3
Not count(0, 0) = 4
Not count(0, 0) = 5
Not count(0, 0) = 6
Not count(0, 0) = 7
Not count(0, 0) = 8
count(0, 1) -> 0
count(0, 1) = 0
Not count(0, 1) = 1
Not count(0, 1) = 2
Not count(0, 1) = 3
Not count(0, 1) = 4
Not count(0, 1) = 5
Not count(0, 1) = 6
Not count(0, 1) = 7
Not count(0, 1) = 8
count(0, 2) -> 0
count(0, 2) = 0
Not count(0, 2) = 1
Not count(0, 2) = 2
Not count(0, 2) = 3
Not count(0, 2) = 4
Not count(0, 2) = 5
Not count(0, 2) = 6
Not count(0, 2) = 7
Not count(0, 2) = 8
count(0, 3) -> 0
count(0, 3) = 0
Not count(0, 3) = 1
Not count(0, 3) = 2
Not count(0, 3) = 3
Not count(0, 3) = 4
Not count(0, 3) = 5
Not count(0, 3) = 6
Not count(0, 3) = 7
Not count(0, 3) = 8
count(0, 4) -> 0
count(0, 4) = 0
Not count(0, 4) = 1
Not count(0, 4) = 2
Not count(0, 4) = 3
Not count(0, 4) = 4
Not count(0, 4) = 5
Not count(0, 4) = 6
Not count(0, 4) = 7
Not count(0, 4) = 8
count(1, 0) -> 0
count(1, 0) = 0
Not count(1, 0) = 1
Not count(1, 0) = 2
Not count(1, 0) = 3
Not count(1, 0) = 4
Not count(1, 0) = 5
Not count(1, 0) = 6
Not count(1, 0) = 7
Not count(1, 0) = 8
count(1, 4) -> 0
count(1, 4) = 0
Not count(1, 4) = 1
Not count(1, 4) = 4
count(2, 0) -> 0
count(2, 0) = 0
Not count(2, 0) = 1
Not count(2, 0) = 2
Not count(2, 0) = 3
Not count(2, 0) = 4
Not count(2, 0) = 5
Not count(2, 0) = 6
Not count(2, 0) = 7
Not count(2, 0) = 8
count(2, 4) -> 0
count(2, 4) = 0
Not count(2, 4) = 1
Not count(2, 4) = 4
count(3, 0) -> 0
count(3, 0) = 0
Not count(3, 0) = 1
Not count(3, 0) = 2
Not count(3, 0) = 3
Not count(3, 0) = 4
Not count(3, 0) = 5
Not count(3, 0) = 6
Not count(3, 0) = 7
Not count(3, 0) = 8
count(3, 4) -> 0
count(3, 4) = 0
Not count(3, 4) = 1
Not count(3, 4) = 4
count(4, 0) -> 0
count(4, 0) = 0
Not count(4, 0) = 1
Not count(4, 0) = 2
Not count(4, 0) = 3
Not count(4, 0) = 4
Not count(4, 0) = 5
Not count(4, 0) = 6
Not count(4, 0) = 7
Not count(4, 0) = 8
count(4, 1) -> 0
count(4, 1) = 0
Not count(4, 1) = 1
Not count(4, 1) = 4
count(4, 2) -> 0
count(4, 2) = 0
Not count(4, 2) = 1
Not count(4, 2) = 4
count(4, 3) -> 0
count(4, 3) = 0
Not count(4, 3) = 1
Not count(4, 3) = 4
count(4, 4) -> 0
count(4, 4) = 0
Not count(4, 4) = 1
Not count(4, 4) = 4
Not shown(0, 0)
Not shown(0, 1)
Not shown(0, 2)
Not shown(0, 3)
Not shown(0, 4)
Not shown(1, 0)
Not shown(2, 0)
Not shown(3, 0)
Not shown(4, 0)
Not shown(1, 4)
Not shown(2, 4)
Not shown(3, 4)
Not shown(4, 1)
Not shown(4, 2)
Not shown(4, 3)
Not shown(4, 4)
Not count(2, 4) = 8
Not count(4, 2) = 8
Not count(3, 4) = 8
Not count(4, 3) = 8
Not count(4, 4) = 8
Not count(1, 4) = 8
Not count(4, 1) = 8
Not count(4, 3) = 2
Not count(4, 4) = 2
Not count(1, 4) = 2
Not count(4, 1) = 2
Not count(2, 4) = 2
Not count(4, 2) = 2
Not count(3, 4) = 2
Not count(3, 4) = 6
Not count(4, 3) = 6
Not count(4, 4) = 6
Not count(1, 4) = 6
Not count(4, 1) = 6
Not count(2, 4) = 6
Not count(4, 2) = 6
Not count(4, 4) = 7
Not count(1, 4) = 7
Not count(4, 1) = 7
Not count(2, 4) = 7
Not count(4, 2) = 7
Not count(3, 4) = 7
Not count(4, 3) = 7
Not count(3, 4) = 5
Not count(4, 3) = 5
Not count(4, 4) = 5
Not count(1, 4) = 5
Not count(4, 1) = 5
Not count(2, 4) = 5
Not count(4, 2) = 5
Not count(4, 3) = 3
Not count(4, 4) = 3
Not count(1, 4) = 3
Not count(4, 1) = 3
Not count(2, 4) = 3
Not count(4, 2) = 3
Not count(3, 4) = 3
Not count(3, 3) = 8
Not count(3, 1) = 7
Not count(3, 1) = 8
Not count(2, 3) = 8
Not count(3, 1) = 5
Not count(3, 3) = 6
Not count(2, 1) = 8
Not count(3, 3) = 7
Not count(3, 2) = 8
Not count(2, 3) = 7
Not count(2, 1) = 7
Not count(1, 1) = 8
Not count(3, 3) = 5
Not count(3, 2) = 7
Not count(1, 3) = 7
Not count(1, 3) = 8
Not count(1, 3) = 6
Not count(3, 1) = 6
Not count(1, 1) = 6
Not count(1, 2) = 7
Not count(1, 1) = 5
Not count(1, 1) = 7
Not count(1, 3) = 5
Not count(1, 2) = 8
No more consequences.
