has_mine(0, 0) -> 0
has_mine(0, 1) -> 0
has_mine(0, 2) -> 0
has_mine(1, 0) -> 0
has_mine(1, 2) -> 0
has_mine(2, 0) -> 0
has_mine(2, 1) -> 0
has_mine(2, 2) -> 0
count(0, 0) -> 0
count(0, 1) -> 0
count(0, 2) -> 0
count(1, 0) -> 0
count(1, 2) -> 0
count(2, 0) -> 0
count(2, 1) -> 0
count(2, 2) -> 0
Not shown(0, 0)
Not shown(0, 1)
Not shown(0, 2)
Not shown(1, 0)
Not shown(1, 2)
Not shown(2, 0)
Not shown(2, 1)
Not shown(2, 2)
No more consequences.
