has_mine(0, 0) -> 0
has_mine(0, 0) = 0
Not has_mine(0, 0) = 1
has_mine(0, 1) -> 0
has_mine(0, 1) = 0
Not has_mine(0, 1) = 1
has_mine(0, 2) -> 0
has_mine(0, 2) = 0
Not has_mine(0, 2) = 1
has_mine(1, 0) -> 0
has_mine(1, 0) = 0
Not has_mine(1, 0) = 1
has_mine(1, 2) -> 0
has_mine(1, 2) = 0
Not has_mine(1, 2) = 1
has_mine(2, 0) -> 0
has_mine(2, 0) = 0
Not has_mine(2, 0) = 1
has_mine(2, 1) -> 0
has_mine(2, 1) = 0
Not has_mine(2, 1) = 1
has_mine(2, 2) -> 0
has_mine(2, 2) = 0
Not has_mine(2, 2) = 1
count(0, 0) -> 0
count(0, 0) = 0
Not count(0, 0) = 1
Not count(0, 0) = 2
Not count(0, 0) = 3
Not count(0, 0) = 4
Not count(0, 0) = 5
Not count(0, 0) = 6
Not count(0, 0) = 7
Not count(0, 0) = 8
count(0, 1) -> 0
count(0, 1) = 0
Not count(0, 1) = 1
Not count(0, 1) = 2
Not count(0, 1) = 3
Not count(0, 1) = 4
Not count(0, 1) = 5
Not count(0, 1) = 6
Not count(0, 1) = 7
Not count(0, 1) = 8
count(0, 2) -> 0
count(0, 2) = 0
Not count(0, 2) = 1
Not count(0, 2) = 2
Not count(0, 2) = 3
Not count(0, 2) = 4
Not count(0, 2) = 5
Not count(0, 2) = 6
Not count(0, 2) = 7
Not count(0, 2) = 8
count(1, 0) -> 0
count(1, 0) = 0
Not count(1, 0) = 1
Not count(1, 0) = 2
Not count(1, 0) = 3
Not count(1, 0) = 4
Not count(1, 0) = 5
Not count(1, 0) = 6
Not count(1, 0) = 7
Not count(1, 0) = 8
count(1, 2) -> 0
count(1, 2) = 0
Not count(1, 2) = 1
Not count(1, 2) = 2
Not count(1, 2) = 3
Not count(1, 2) = 4
Not count(1, 2) = 5
Not count(1, 2) = 6
Not count(1, 2) = 7
Not count(1, 2) = 8
count(2, 0) -> 0
count(2, 0) = 0
Not count(2, 0) = 1
Not count(2, 0) = 2
Not count(2, 0) = 3
Not count(2, 0) = 4
Not count(2, 0) = 5
Not count(2, 0) = 6
Not count(2, 0) = 7
Not count(2, 0) = 8
count(2, 1) -> 0
count(2, 1) = 0
Not count(2, 1) = 1
Not count(2, 1) = 2
Not count(2, 1) = 3
Not count(2, 1) = 4
Not count(2, 1) = 5
Not count(2, 1) = 6
Not count(2, 1) = 7
Not count(2, 1) = 8
count(2, 2) -> 0
count(2, 2) = 0
Not count(2, 2) = 1
Not count(2, 2) = 2
Not count(2, 2) = 3
Not count(2, 2) = 4
Not count(2, 2) = 5
Not count(2, 2) = 6
Not count(2, 2) = 7
Not count(2, 2) = 8
Not shown(0, 0)
Not shown(0, 1)
Not shown(0, 2)
Not shown(1, 0)
Not shown(1, 2)
Not shown(2, 0)
Not shown(2, 1)
Not shown(2, 2)
Not count(1, 1) = 7
Not count(1, 1) = 8
Not count(1, 1) = 3
Not count(1, 1) = 4
Not count(1, 1) = 5
Not count(1, 1) = 6
Not count(1, 1) = 2
No more consequences.
