Vertices := 3.
Type := triangle.
Length := {1 -> 1, 2 -> 1, 3 -> 1, 4 -> 0}.
Angle := {1 -> 60, 2 -> 60, 3 -> 60, 4 -> 0}.
Convex := true.
Equilateral := true.

Vertices := 3.
Type := triangle.
Length := {1 -> 1, 2 -> 1, 3 -> 1, 4 -> 0}.
Angle := {1 -> 60, 2 -> 60, 3 -> 60, 4 -> 0}.
Convex := true.
Equilateral := true.


Model 1
==========
Vertices := 3.
Type := triangle.
Length := {1 -> 1, 2 -> 1, 3 -> 1, 4 -> 0}.
Angle := {1 -> 60, 2 -> 60, 3 -> 60, 4 -> 0}.
Convex := true.
Equilateral := true.
Large := {}.
Wide := {}.


More models may be available.  Change the max argument to see them.
