Vertices := 3.
Type := triangle.
Length := {1 -> 1.0, 2 -> 1.0, 3 -> 1.0, 4 -> 0.0}.
Angle := {1 -> 60.0, 2 -> 60.0, 3 -> 60.0, 4 -> 0.0}.
Convex := true.
Equilateral := true.

Vertices := 3.
Type := triangle.
Length := {1 -> 1.0, 2 -> 1.0, 3 -> 1.0, 4 -> 0.0}.
Angle := {1 -> 60.0, 2 -> 60.0, 3 -> 60.0, 4 -> 0.0}.
Convex := true.
Equilateral := true.


Model 1
==========
Vertices := 3.
Type := triangle.
Length := {1 -> 1.0, 2 -> 1.0, 3 -> 1.0, 4 -> 0.0}.
Angle := {1 -> 60.0, 2 -> 60.0, 3 -> 60.0, 4 -> 0.0}.
Convex := true.
Equilateral := true.
Large := {}.
Wide := {}.


More models may be available.  Change the max argument to see them.
