
Model 0
==========
[q = False, p = True]

Model 1
==========
[q = False, p = True]

Model 2
==========
[q = False, p = True]

Model 3
==========
[q = False, p = True]

Model 4
==========
[q = False, p = True]

Model 5
==========
[q = False, p = True]

Model 6
==========
[q = False, p = True]

Model 7
==========
[q = False, p = True]

Model 8
==========
[q = False, p = True]

Model 9
==========
[q = False, p = True]
